### ISSUE TITLE
The module require a .env file

### ISSUE THREAD

**Issue by ky23** [dial-once/node-phone-utils#15]
The module require a .env file to use it for hlr-lookup, but even if it's not an hlr-lookup the module still require the .env file, I've tried to add an empty .env, and it worked.

**Comment by PuKoren** [comment]
You mean the module crash when you require it without having a .env file?

**Comment by mrister** [comment]
Yeah. This needs a refactor. To use .env file only when necessary an this is when using hlrLookup.
