### ISSUE TITLE
Do not use 'getInstance' when not using 'Singletons'

### ISSUE THREAD

**Issue by PuKoren** [dial-once/node-phone-utils#7]
Example:
https://github.com/dial-once/node-phone-utils/blob/master/lib/validators/phone_number_validator.js#L101

``getInstance`` is always returning a new object, the function naming is misleading, we can either assign the function directly to ``module.exports`` or rename it to something like ``createInstance``.

**Comment by mrister** [comment]
Renamed to createInstance.
